# Generated by Django 5.0.3 on 2024-04-12 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("second_hw_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageProduct",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="second_hw_app.product",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default=None, upload_to="", verbose_name="Product image"
                    ),
                ),
            ],
            bases=("second_hw_app.product",),
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("-added",),
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.RenameField(
            model_name="order",
            old_name="product",
            new_name="products",
        ),
    ]
