# Generated by Django 5.0.3 on 2024-04-08 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("second_hw_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="product",
            new_name="products",
        ),
    ]
