# Generated by Django 5.0.3 on 2024-04-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("second_hw_app", "0002_rename_product_order_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default=None, upload_to="", verbose_name="Product image"
            ),
        ),
    ]
